---
# tasks file for ansible-role-docker

- name: Incule variables
  include_vars: '{{ ansible_os_family }}.yml'
  tags:
    - always

- name: Configure system
  include_tasks: '{{ platform }}'
  with_first_found:
    - 'system/{{ ansible_os_family }}.yml'
    - system/not-supported.yml
  loop_control:
    loop_var: platform
  tags:
    - setup

- name: Prepare system
  include_tasks: prepare-gitlab-runner.yml
  tags:
    - setup

- name: Install GitLab agent {{ gitlab_runner_install_package }}
  package:
    name: '{{ gitlab_runner_install_package }}'
    state: present
    update_cache: true
  register: installed_gitlab
  until: installed_gitlab is succeeded
  become: true
  notify: kick gitlab-runner

- name: Configure gitlab-runner daemon
  include_tasks: config-gitlab-runner.yml
  tags:
    - setup
    - upd_conf
