---
# tasks file for ansible-role-docker

- name: Incule variables
  include_vars: '{{ ansible_os_family }}.yml'
  tags:
    - always

- name: Prepare system
  include_tasks: prepare-gitlab-runner.yml
  tags:
    - setup

- name: Configure system
  include_tasks: '{{ platform }}'
  with_first_found:
    - 'system/{{ ansible_os_family }}.yml'
    - system/not-supported.yml
  loop_control:
    loop_var: platform
  tags:
    - setup

- name: Configure gitlab-runner daemon
  include_tasks: config-gitlab-runner.yml
  tags:
    - setup
    - upd_conf
