---
- name: Become section
  block:
    - name: Add universe repository for Ubuntu
      apt_repository:
        repo: 'deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe'
        state: present
      when: ansible_distribution_release == 'bionic'

    - name: Install GitLab through deb package
      apt:
        deb: '{{ gitlab_runner_deb_repo }}'
      register: install_gitlab_runner
      until: install_gitlab_runner is succeeded
  become: true
  tags:
    - always
