---
- name: Become section
  block:
    - name: Add universe repository for Ubuntu
      apt_repository:
        repo: 'deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe'
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Add GitLab Runner GPG key
      apt_key:
        url: '{{ gitlab_runner_gpg }}'
      register: apt_key_result
      until: apt_key_result is succeeded
      
    - name: Add GitLab Runner repository
      apt_repository:
        repo: '{{ gitlab_runner_repo }}'
        validate_certs: true

    #- name: Install GitLab through deb package
    #  apt:
    #    deb: '{{ gitlab_runner_deb_repo }}'
    #  register: install_gitlab_runner
    #  until: install_gitlab_runner is succeeded
    - name: Install GitLab agent {{ gitlab_runner_install_package }}
      apt:
        name: '{{ gitlab_runner_install_package }}'
        state: present
        update_cache: true
      register: installed_gitlab
      until: installed_gitlab is succeeded
      notify: kick gitlab-runner
  become: true
  tags:
    - always
