---
- name: Install ansible selinux support library
  yum:
    name: '{{ yum_libselinux_python_library }}'
    state: present
  register: status
  until: status is succeeded
  become: true
  tags:
    - always

- name: Install ansible selinux configure libraries
  yum:
    name: '{{ yum_libselinux_config_libraries }}'
    state: present
  register: status
  until: status is succeeded
  become: true
  when: ansible_selinux.status == 'enabled'
  tags:
    - always
