---
- name: Install ansible selinux support library
  yum:
    name: libselinux-python
    state: present
  register: status
  until: status is succeeded
  become: true
  tags:
    - always

- name: Install ansible selinux configure libraries
  yum:
    name:
      - policycoreutils-python
      - libsemanage-python
    state: present
  register: status
  until: status is succeeded
  become: true
  when: ansible_selinux.status == 'enabled'
  tags:
    - always
