---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-gitlab-runner
      vars:
        gitlab_runner_concurrent: 4
        gitlab_runner_skip_registration: false
        gitlab_api_token: >-
          {{ lookup('env', 'gitlab_api_token') }}
        gitlab_ci_token: >-
          {{ lookup('env', 'gitlab_registration_token') }}
        gitlab_runner_description: '{{ inventory_hostname }}'
        gitlab_runner_tags:
          - molecule_test
          - '{{ ansible_distribution | lower }}'
        gitlab_runner_untagged_builds_run: false
