---
- name: Include common prepare
  import_playbook: ../resources/provisioning/AWS/prepare.yml

- name: Prepare RHEL
  hosts: rhel8
  tasks:

    - name: Install python3-devel
      yum:
        name:
          - gcc
          - openssl-devel
          - python3-devel
        state: present
      register: status
      until: status is succeeded
      become: true
