---
- name: Converge | Centos
  hosts: rhel_family
  roles:
    - role: ansible-role-gitlab-runner
      vars:
        gitlab_runner_concurrent: 1
        gitlab_runner_skip_registration: True

- name: Converge | Ubuntu
  hosts: debian_family
  roles:
    - role: ansible-role-gitlab-runner
      vars:
        gitlab_runner_concurrent: 4
        gitlab_runner_skip_registration: True
