---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: delegated
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-aws-centos7-ansible-role-gitlab-runner
    image: CentOS7_64-bit
    shape: small
    region: AWS-EUCENTRAL
    wait_timeout: 1800
    groups:
      - rhel_family
  - name: test-aws-ubuntu1804-ansible-role-gitlab-runner
    image: Ubuntu18.04_64-bit
    shape: small
    region: AWS-EUCENTRAL
    wait_timeout: 1800
    groups:
      - debian_family
provisioner:
  name: ansible
  # log: True
  playbooks:
    create: ../resources/provisioning/EPC/create.yml
    prepare: ../resources/provisioning/EPC/prepare.yml
    destroy: ../resources/provisioning/EPC/destroy.yml
  config_options:
    ssh_connection:
      control_path: "/var/ans/%%h"
  lint:
    name: ansible-lint
  env:
    ANSIBLE_LIBRARY: ${ANSIBLE_LIBRARY}
scenario:
  name: cloud-aws-delegated
verifier:
  name: testinfra
  options:
    verbose: true
  directory: ../resources/tests/
  lint:
    name: flake8
